### PR TITLE
Add support for bitfields

### PR DESCRIPTION
**Pull request by chocola-mint**
This PR adds support for marking C++ enums as Godot bitfields. using the `REG_BITFIELD()` macro.

### CODE REVIEW

**Review by haraldwer — COMMENTED** [review]
Maybe "Bitfield" could be an optional parameter for the existing REG_ENUM macro? It feels weird to have two defines that both handle enums

**Comment by haraldwer** [comment]
I know I havent specified code guidelines, but Im still trying to keep the code consistent. There are some inconcitencies in the code formatting. This is my principle: 
Skipping {} is ok for one-liners, but the following statement should still be on a new line. For example:
```
if (condition)
   DoSomething()
```
Is preferred over
```
if (condition) DoSomething()
```
And 
```
if (condition)
{
   DoSomething()
}
```
This also applies for `continue`, `return` and `break`.

**Comment by chocola-mint** [comment]
> Maybe "Bitfield" could be an optional parameter for the existing REG_ENUM macro? It feels weird to have two defines that both handle enums

I've thought about that too, but this would bring us to the issue of defining parameters specific to REG macros. 

With `REG_PROPERTY` the parameters are forwarded as PropertyInfo parameters, and it's pretty readable there because godot-cpp already comes with macros for property hints, etc.

Here, we could settle with a single boolean parameter (`REG_ENUM(true)` means it's a bitfield), but this kind of parameter formatting wouldn't look very readable at a glance. You can also imagine how ugly this would look if we have more parameters for other REG macros.

We could also add our own macros or enums (maybe `REG_ENUM_AS_BITFIELD`) and parse for these tags too, which does involve a lot more typing but comes with IDE autocomplete and is still pretty readable. Maybe with a `<tag> = <value>` syntax, kind of like Unreal's meta properties. What do you think?

> I know I havent specified code guidelines, but Im still trying to keep the code consistent. There are some inconcitencies in the code formatting. This is my principle: Skipping {} is ok for one-liners, but the following statement should still be on a new line.

Noted, will fix later.

**Comment by haraldwer** [comment]
Valid points. I believe we will soon encounter other situations where parameters will be needed for our macros, so lets prepare for that. I think that the Unreal approach is good. In our case, that could look like:
```
REG_ENUM(Bitfield)
```

Having defines for parameters sounds like a good idea for IDE autocompletion. I want the naming scheme of parameter macros to communicate how they are supposed to be used. Something like `REG_P_<param name>`, although this might be a bit too verbose...

Anyways here is what that would look like in the example from above:
```
REG_ENUM(REG_P_Bitfield)
```

For REG_PROPERTY(), maybe the PropertyInfo data could be forwarded using a different syntax. Here is my suggestion:
```
REG_PROPERTY(Info="<PropertyInfo params>")
```
This makes it easy to expand the macro with other parameters in the future. 

Whats your opinion?

**Comment by chocola-mint** [comment]
`REG_P_<param name>` sounds good to me.

As for REG_PROPERTY(), putting PropertyInfo parameters inside strings would hide them from IDE autocompletion. I suggest using parentheses instead:
```
REG_PROPERTY(REG_P_Info = (<PropertyInfo params>), ... )
```

**Comment by haraldwer** [comment]
Alright, lets go with REG_P_ and parentheses

**Comment by chocola-mint** [comment]
I've implemented the new meta property system. Note that meta properties are implemented as key-value pairs (Dictionaries), and there can be key-only properties (like here, `REG_P_Bitfield` is such a property).

`Pattern_Function` still needs to be updated to use this new syntax, but that's outside the scope of this PR.

As much as I am used to writing code without unit tests thanks to game jams, I think we're getting to the point where setting up unit tests would save us a lot of trouble later on when debugging or adding new features.

**Comment by haraldwer** [comment]
You are incredibly quick! Looks good 👍 Lets discuss unit testing in a separate issue

**Pull request merged**
